### PR TITLE
Add docker-compose optional test environment

### PR DESCRIPTION
**Pull request by nkonev**

### CODE REVIEW

**Comment by nkonev** [comment]
@vladmihalcea can you merge it ?

**Comment by vladmihalcea** [comment]
@nkonev I'm currently very busy with my video courses. I'll review it when I have more time.

**Comment by nstdio** [comment]
Why just not use the https://github.com/testcontainers/testcontainers-java to have isolated self contained test environment for each test?

**Comment by vladmihalcea** [comment]
That's an option. But, I don't have time to investigate it. There's also a similar Pull Request for Docker Compose, but since the amount of contributions is low, this is not a big priority for the moment.

**Comment by nkonev** [comment]
I see testcontainers would be more cool than ugly docker-compose.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
