### PR TITLE
Replace reflection usage in PostgreSQL Types with Driver-specific API calls

### PR DESCRIPTION
**Pull request by nstdio**

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Reflection usage is intentional. Without it, a mandatory dependency on PostgreSQL Driver will be needed, and that's not desirable since the framework can be used for MySQL only.

**Comment by nstdio** [comment]
I don't understand how it's mandatory? We add postgres driver as a provided dependency...

**Comment by vladmihalcea** [comment]
Ok, I'll investigate it then.

**Comment by vladmihalcea** [comment]
Applied. Thanks.

**Pull request closed without merging**
