### PR TITLE
Add support for PostgeSQL range type.

### PR DESCRIPTION
**Pull request by nstdio**

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks. I'll check it out when I have some time.

**Comment by vladmihalcea** [comment]
@nstdio I integrated it. Thanks.

**Comment by nstdio** [comment]
@vladmihalcea Thanks. Would it be appropriate to make `Range` API more rich ?

For example some how expose/adapt [this functions](https://www.postgresql.org/docs/current/functions-range.html) at Java level.

**Comment by vladmihalcea** [comment]
All those operators can be accessed via native SQL. The goal of this framework is just to allow Hibernate to persist database-specific column types.

**Comment by AbdulR3hman** [comment]
@vladmihalcea any plans on releasing this soon?

**Comment by vladmihalcea** [comment]
@AbdulR3hman I'll integrate [this PR first](https://github.com/vladmihalcea/hibernate-types/pull/64),and then release a new version in the following two weeks.

**Pull request closed without merging**
