### PR TITLE
Refactor support for List, Set, Map to be saved as JSON

### PR DESCRIPTION
**Pull request by quaff**
Use JavaXMember.getJavaType() to get generic type, then use ObjectMapper.getTypeFactory().constructType() to deserialize json.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks. I'm going to review it only after the 1st of February since I'm now busy finishing the first part of my video course.

**Comment by vladmihalcea** [comment]
@quaff Wow! That's super smart. Thanks for providing this Pull Request. I'm going to enhance it a little bit, integrate it and release it now.

**Comment by vladmihalcea** [comment]
It's integrated into 2.0.0 now and available on Maven Central. Thanks.

**Comment by quaff** [comment]
Can you handle this https://hibernate.atlassian.net/projects/HCANN/issues/HCANN-83 ?

**Comment by vladmihalcea** [comment]
As you can see, I'm also waiting for my [Pull Request](https://github.com/hibernate/hibernate-commons-annotations/pull/11) to be integrated in Hibernate Commons Annotations.

**Pull request closed without merging**
