### PR TITLE
Allow JSON Types to handle parameterized entity attribute type variables

### PR DESCRIPTION
**Pull request by charllie**
Handle TypeVariable type

For instance:

```java
@Entity
@TypeDef(name = ColumnTypes.JSON_BINARY, typeClass = JsonBinaryType.class)
@DiscriminatorColumn(name = Columns.TYPE)
public class MyClass<T> {
  @Type(type = ColumnTypes.JSON_BINARY)
  @Column(columnDefinition = ColumnTypes.JSON_BINARY)
  private T something;
}
```

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks, I'll review it when I have some time.

**Comment by charllie** [comment]
> Thanks, I'll review it when I have some time.

No problem, thanks for your library BTW 👍

**Comment by vladmihalcea** [comment]
@charllie You're welcome. Stay tuned for the 2.10 release.

**Comment by vladmihalcea** [comment]
[This test case](https://github.com/vladmihalcea/hibernate-types/commit/d392ef14dd75fec4020b6ea5c61a4d0f1d811f1a) proves that everything works fine even without your change.

If you provide a replicating test case that proves there's a need for this change, I will reopen the issue.

**Comment by charllie** [comment]
Thanks for your reply.

Indeed, this test case is working. I did a project with a failing scenario but I am not able to reproduce it with your test case model.

If you have some times, you can take a look at https://github.com/charllie/hibernate-types-52-spring-boot (failing in BookStarter class)

**Comment by vladmihalcea** [comment]
Applied upstream. Thanks.

**Pull request closed without merging**
