### PR TITLE
Improve logging of array parameters in BasicBinder

### PR DESCRIPTION
**Pull request by dpolivaev**
Before:
~~~
binding parameter [3] as [ARRAY] - [[Lcom.xxx.yyy.zzz.xxx.api.SampleTriggers;@5c3ef336]
~~~
Now:
~~~
binding parameter [3] as [ARRAY] - [[PURCHASE_CONFIRMATION]::SampleTriggers[]]
~~~

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. I'll review it when I have some time.

**Comment by vladmihalcea** [comment]
Thanks for the PR. I noticed that the Hibernate `PrimitiveByteArrayTypeDescriptor` does not truncate the data. More, using the Hibernate logging is not the best way to log statements. You are better off using [datasource-proxy](https://vladmihalcea.com/the-best-way-to-log-jdbc-statements/).

So, even if this PR is merged, it will not work for other logging solutions. Therefore, you should restrict the size of logged messages in the Log framework.

**Comment by vladmihalcea** [comment]
I reopened it because I thought the issue was about truncating the array. I'll integrate it without truncation.

**Comment by dpolivaev** [comment]
The purpose of truncation was to avoid possible megabytes of data logged as nobody can know the array lengths in general.

**Comment by dpolivaev** [comment]
But you are right, it was mainly not about truncation.

**Comment by vladmihalcea** [comment]
Thanks, I merged it.

**Pull request closed without merging**
