### PR TITLE
Reproducer for vladmihalcea/hibernate-types#243

### PR DESCRIPTION
**Pull request by pavelgordon**
Hey! 
Based on [issue 243](https://github.com/vladmihalcea/hibernate-types/issues/243), here is a provided test which reproduced the problem.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for providing me a test case. I will be quite busy in the upcoming 3 months, so I think I'll investigate it in the second half of December or the beginning of January.

**Comment by pavelgordon** [comment]
I decided to implement the fix for it by myself, using the advice you have me in issue discussion. Now tests are green again.
Please review this PR when you will have time.

**Comment by vladmihalcea** [comment]
Great. Thanks for taking the time to fix it. I'll review it when I have some time.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
