### PR TITLE
change constructor type args from Class to Type

### PR DESCRIPTION
**Pull request by andyflury**
The JsonStringType constructor args Class are only used when calling the constructor of JsonTypeDescriptor which expects a Type argument. There is no need for the JsonStringType constructor arg to be more restrictive (Class) then the JsonTypeDescriptor arg (Type). 

This causes an issue when grammatically registering the JsonStringType and injecting a java.lang.reflect.ParameterizedType (e.g. HashMap<String,Object>)

### CODE REVIEW

**Comment by vladmihalcea** [comment]
In order to integrate this change, I need a test case that proves why we need this modification. Therefore, you need to amend your PR to include the same test case you described in the issue that led to this change request.

**Comment by andyflury** [comment]
I've add MySQLGenericConfigJsonTypeTest. It programatically registers the `JsonStringType` using a ParameterizedType (HashMap<String,Object>). It adds a new Entity `PropertyHolder` that contains a HashMap property (`props`) that is persisted into a json column. The `props` property can hold objects as well as POJO.

Without the Constructor changes this test case will fail.

Feel free to make any changes you find necessary.

**Comment by vladmihalcea** [comment]
Thanks. I'll check it out when I have some time.

**Comment by andyflury** [comment]
Thanks! I added a ParametrizedJsonStringType subclass so that it can be used alongside the default JsonStringType

**Comment by andyflury** [comment]
@vladmihalcea I believe I figured out away to get around the constructor arg problem by having my ParametrizedJsonStringType extend AbstractSingleColumnStandardBasicType instead of JsonStringType:

```
public class ParametrizedJsonStringType extends AbstractSingleColumnStandardBasicType<Object> implements DynamicParameterizedType {

    public ParametrizedJsonStringType(final String name, final Type rawType, final Type[] actualTypeArguments) {
        super(
                JsonStringSqlTypeDescriptor.INSTANCE,
                new JsonTypeDescriptor(new ObjectMapperWrapper(createObjectMapper()), createParameterizedType(rawType, actualTypeArguments, null))
        );
    }
```

With this my solution works without any modifications of your library.

Nevertheless I think It would be good to change the constructor args of JsonStringType to Type instead of Class. Up to you!

Thanks for your help along the way!

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
