### PR TITLE
Add missing type INSTANCE constants

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**
Useful for binding the types to native queries.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks. I'll integrate it as soon as I have some spare time.

**Comment by JWGmeligMeyling** [comment]
Don't rush 😄 You're well aware that it took me long enough to find the time to make these contributions available

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Comment by JWGmeligMeyling** [comment]
Thanks!

**Pull request closed without merging**
