### PR TITLE
NPE thrown by AbstractArrayTypeDescriptor#setParameterValues when creating a PostgreSQL ARRAY

### PR DESCRIPTION
**Pull request by jones-gareth**
Simple fix for the error in issue https://github.com/vladmihalcea/hibernate-types/issues/142

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks. I'll review it when I have some time.

**Comment by Omenien** [comment]
@vladmihalcea any chance this review can get bumped up in priority?

**Comment by vladmihalcea** [comment]
I was very busy and didn't have time for this project. I hope I'll have some time in December.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
